/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export class QuicClient {
  static new(rpcUrl: string, wsUrl: string): QuicClient
  connect(): Promise<void>
  sendTransaction(txSlice: Uint8Array): Promise<string>
  onProgramAccountChange(pubkey: string, config: any, tsfn: (err: Error | null, arg: string) => any): Promise<void>
}
